options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Docker Build & Push（並列）
  - id: build-and-push
    name: "gcr.io/cloud-builders/docker"
    entrypoint: bash
    args:
      - "-c"
      - |
        SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)
        for dir in backend/*/; do
          svc=$(basename "$dir")
          echo "Building $svc"
          docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-hisho-backend/$svc:$SHORT_SHA "$dir" &
        done
        wait

        for dir in backend/*/; do
          svc=$(basename "$dir")
          echo "Pushing $svc"
          docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-hisho-backend/$svc:$SHORT_SHA &
        done
        wait

  # Cloud Run Deploy（並列）
  - id: deploy
    name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: bash
    args:
      - "-c"
      - |
        SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)
        for dir in backend/*/; do
          svc=$(basename "$dir")
          echo "Deploying $svc to Cloud Run"
          gcloud run deploy "$svc" \
            --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/ai-hisho-backend/$svc:$SHORT_SHA \
            --region=asia-northeast1 \
            --platform=managed \
            --update-secrets=/etc/secrets/firebase-${svc}/firebase-credentials.json=firebase-credentials:latest \
            --set-env-vars=GOOGLE_APPLICATION_CREDENTIALS=/etc/secrets/firebase-${svc}/firebase-credentials.json \
            --quiet &
        done
        wait
